### ISSUE TITLE
Dajcie namiar na cebulę od kazikuw

### ISSUE THREAD

**Issue by Igreky** [Filippuuu/czekolada#1]
https://user-images.githubusercontent.com/39243548/103458777-971a6300-4d0b-11eb-8a4f-7bdd5d53c54d.mp4

**Comment by 05xapresses** [comment]
co jest z tobą nie tak @Igreky

**Comment by Igreky** [comment]
Idk

**Comment by Igreky** [comment]
Po prostu postnąłem jakiś shitpost, bo i tak to jest bezwartościowe repo

**Comment by Filippuuu** [comment]
Co
